### ISSUE TITLE
win 22631(23H2) get AsyncKeyState fail

### ISSUE THREAD

**Issue by o2e** [Metick/DMALibrary#2]
Winver: 22631.2861 
InputManager  -> gafAsyncKeyStateExport. https://github.com/Metick/DMALibrary/blob/a44adab2cc99d99a9f30da6f86778a9b1516047e/DMALibrary/Memory/InputManager.cpp#L24

The code to get the `user_session_state` doesn't seem to be working, as evidenced by the fact that it doesn't read the correct value during the second step.

The following code is a demo of the code I split when I was conducting my research.

It reads 4 pid's 4 uses seems to be the same, do you have any suggestions?

Thank you for your work.

<img width="1286" alt="image" src="https://github.com/Metick/DMALibrary/assets/24642961/079fe6db-931c-4c42-962e-ef72df673fdc">

**Comment by o2e** [comment]
Here's the ReadMemory function I improvised.
```cpp
template<typename T> T ReadMemory(uintptr_t address, DWORD m_pid) {
     T buffer{};
     DWORD bytes_read = 0;
     VMMDLL_MemReadEx(vmmHandle, m_pid, address, (PBYTE) &buffer, sizeof(T), &bytes_read, VMMDLL_FLAG_NOCACHE);
     return buffer;
}

```

**Comment by Metick** [comment]
Sorry for the late reply, It seems like the class isn't being instanced correctly making it nolonger have the previous initialized keyboard. I'll fix it later today.

Also another issue that can be the cause is that windows memory manager that pages out the base-page which is required for parsing. there is nothing I can do about it. It's there on a freshly booted computer though and goes away after a while, and may return at random later on.

Usually restarting the target computer will fix it aswell..

**Comment by Metick** [comment]
Sorry for taking so long, i've finally taken time to solve the issue that was existing within the library related to keyboard input.
