### ISSUE TITLE
Main PC Keyboard issue.

### ISSUE THREAD

**Issue by TheCollectorIsSad** [Metick/DMALibrary#8]
Seems like the keyboard sometimes doesn't want to initialize and a restart normally fixes it but was curious if it's possible to fix it. I think the offsets might change sometimes which causes the issue but unsure.

**Comment by Metick** [comment]
It has nothing to do with offsets or being outdated. It's windows memory manager that pages out the base-page which is required for parsing. there is nothing I can do about it. It's there on a freshly booted computer though and goes away after a while, and may return at random later on.

You can manually restart winlogon.exe and it usually appears back, otherwise restarting your computer also fixes it.
